name: Docker Image CI

on:
  push:
    branches:
      -  main

env:
  IMAGE_NAME: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/http-hitting-test

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
  
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish & Push to registry
        run: dotnet publish
